# Generated by Django 4.2.4 on 2023-08-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_message_sender', '0004_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='chatId',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
