# Generated by Django 4.2.4 on 2023-08-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_message_sender', '0005_extendeduser_chatid_alter_extendeduser_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='chatId',
            new_name='chat_id',
        ),
    ]
