# Generated by Django 4.2.4 on 2023-08-15 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_message_sender', '0006_rename_chatid_extendeduser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='chat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
